#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Lahman2009")]
	public partial class BaseballDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BaseballDataContext() : 
				base(global::Repository.Properties.Settings.Default.Lahman2009ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BaseballDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseballDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseballDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseballDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BatterDetail> BatterDetails
		{
			get
			{
				return this.GetTable<BatterDetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BatterDetail")]
	public partial class BatterDetail
	{
		
		private string _playerID;
		
		private string _nameFirst;
		
		private string _nameLast;
		
		private short _yearID;
		
		private string _teamID;
		
		private string _TeamName;
		
		private double _salary;
		
		private short _G;
		
		private System.Nullable<short> _AB;
		
		private System.Nullable<short> _R;
		
		private short _H;
		
		private short @__2B;
		
		private short @__3B;
		
		private short _HR;
		
		private short _RBI;
		
		private System.Nullable<short> _SB;
		
		private System.Nullable<short> _BB;
		
		public BatterDetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playerID", DbType="NVarChar(10)")]
		public string playerID
		{
			get
			{
				return this._playerID;
			}
			set
			{
				if ((this._playerID != value))
				{
					this._playerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameFirst", DbType="NVarChar(50)")]
		public string nameFirst
		{
			get
			{
				return this._nameFirst;
			}
			set
			{
				if ((this._nameFirst != value))
				{
					this._nameFirst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nameLast", DbType="NVarChar(50)")]
		public string nameLast
		{
			get
			{
				return this._nameLast;
			}
			set
			{
				if ((this._nameLast != value))
				{
					this._nameLast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yearID", DbType="SmallInt NOT NULL")]
		public short yearID
		{
			get
			{
				return this._yearID;
			}
			set
			{
				if ((this._yearID != value))
				{
					this._yearID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teamID", DbType="NVarChar(3)")]
		public string teamID
		{
			get
			{
				return this._teamID;
			}
			set
			{
				if ((this._teamID != value))
				{
					this._teamID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamName", DbType="NVarChar(50)")]
		public string TeamName
		{
			get
			{
				return this._TeamName;
			}
			set
			{
				if ((this._TeamName != value))
				{
					this._TeamName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="Float")]
		public double salary
		{
			get
			{
				return this._salary;
			}
			set
			{
				if ((this._salary != value))
				{
					this._salary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G", DbType="SmallInt")]
		public short G
		{
			get
			{
				return this._G;
			}
			set
			{
				if ((this._G != value))
				{
					this._G = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AB", DbType="SmallInt")]
		public System.Nullable<short> AB
		{
			get
			{
				return this._AB;
			}
			set
			{
				if ((this._AB != value))
				{
					this._AB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="SmallInt")]
		public System.Nullable<short> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H", DbType="SmallInt")]
		public short H
		{
			get
			{
				return this._H;
			}
			set
			{
				if ((this._H != value))
				{
					this._H = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2B]", Storage="__2B", DbType="SmallInt")]
		public short _2B
		{
			get
			{
				return this.@__2B;
			}
			set
			{
				if ((this.@__2B != value))
				{
					this.@__2B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3B]", Storage="__3B", DbType="SmallInt")]
		public short _3B
		{
			get
			{
				return this.@__3B;
			}
			set
			{
				if ((this.@__3B != value))
				{
					this.@__3B = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HR", DbType="SmallInt")]
		public short HR
		{
			get
			{
				return this._HR;
			}
			set
			{
				if ((this._HR != value))
				{
					this._HR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RBI", DbType="SmallInt")]
		public short RBI
		{
			get
			{
				return this._RBI;
			}
			set
			{
				if ((this._RBI != value))
				{
					this._RBI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SB", DbType="SmallInt")]
		public System.Nullable<short> SB
		{
			get
			{
				return this._SB;
			}
			set
			{
				if ((this._SB != value))
				{
					this._SB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BB", DbType="SmallInt")]
		public System.Nullable<short> BB
		{
			get
			{
				return this._BB;
			}
			set
			{
				if ((this._BB != value))
				{
					this._BB = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
